# Generated by Django 6.0.5 on 2026-07-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("question", models.CharField(max_length=180)),
                ("answer", models.TextField()),
            ],
            options={
                "ordering": ("order", "id"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Inquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("company", models.CharField(blank=True, max_length=120)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("service", models.CharField(max_length=100)),
                ("budget", models.CharField(blank=True, max_length=80)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_contacted", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name_plural": "Inquiries",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="NavigationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("label", models.CharField(max_length=40)),
                ("url", models.CharField(max_length=120)),
            ],
            options={
                "ordering": ("order", "id"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProcessStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=50)),
                ("description", models.TextField()),
            ],
            options={
                "ordering": ("order", "id"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=100)),
                ("summary", models.TextField()),
                ("result", models.CharField(max_length=100)),
                ("image_url", models.URLField(blank=True)),
                ("image", models.ImageField(blank=True, upload_to="projects/")),
                ("project_url", models.URLField(blank=True)),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("lime", "Lime"),
                            ("violet", "Violet"),
                            ("orange", "Orange"),
                        ],
                        default="lime",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("number", models.CharField(blank=True, max_length=5)),
                ("title", models.CharField(max_length=80)),
                ("description", models.TextField()),
                (
                    "icon",
                    models.CharField(
                        default="asterisk",
                        help_text="Decorative icon name",
                        max_length=40,
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        help_text="Comma-separated capabilities", max_length=180
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="The Webfix", max_length=80)),
                ("logo_text", models.CharField(default="THE WEBFIX", max_length=30)),
                (
                    "announcement",
                    models.CharField(
                        default="Independent digital studio · India / Worldwide",
                        max_length=140,
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        default="The Webfix — Digital experiences built to perform",
                        max_length=70,
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        default="The Webfix creates category-defining websites, campaigns and digital products that turn ambitious brands into market leaders.",
                        max_length=170,
                    ),
                ),
                (
                    "keywords",
                    models.CharField(
                        default="digital agency, Django development, branding, SEO, performance marketing",
                        max_length=255,
                    ),
                ),
                ("canonical_url", models.URLField(blank=True)),
                ("og_image", models.URLField(blank=True)),
                (
                    "hero_eyebrow",
                    models.CharField(
                        default="Strategy · Design · Technology · Growth",
                        max_length=100,
                    ),
                ),
                (
                    "hero_title",
                    models.CharField(
                        default="We turn bold ideas into digital momentum.",
                        max_length=180,
                    ),
                ),
                (
                    "hero_subtitle",
                    models.TextField(
                        default="An independent digital growth studio building memorable brands, high-performance products and campaigns engineered to compound."
                    ),
                ),
                (
                    "primary_cta_text",
                    models.CharField(default="Start a project", max_length=40),
                ),
                (
                    "primary_cta_url",
                    models.CharField(default="#contact", max_length=120),
                ),
                (
                    "secondary_cta_text",
                    models.CharField(default="Explore our work", max_length=40),
                ),
                (
                    "secondary_cta_url",
                    models.CharField(default="#work", max_length=120),
                ),
                (
                    "about_eyebrow",
                    models.CharField(default="Built for the ambitious", max_length=70),
                ),
                (
                    "about_title",
                    models.CharField(
                        default="Not another agency. Your unfair digital advantage.",
                        max_length=180,
                    ),
                ),
                (
                    "about_body",
                    models.TextField(
                        default="The Webfix brings senior strategy, obsessive craft and measurable growth into one focused team. We partner with businesses ready to challenge the expected—and build the systems that move them forward."
                    ),
                ),
                (
                    "contact_title",
                    models.CharField(
                        default="Let’s make your next move impossible to ignore.",
                        max_length=150,
                    ),
                ),
                (
                    "contact_body",
                    models.TextField(
                        default="Tell us where you want to go. We’ll bring clarity, creative firepower and a practical route to get there."
                    ),
                ),
                (
                    "email",
                    models.EmailField(default="hello@thewebfix.com", max_length=254),
                ),
                ("phone", models.CharField(default="+91 98765 43210", max_length=40)),
                ("whatsapp_url", models.URLField(default="https://wa.me/919876543210")),
                (
                    "address",
                    models.CharField(
                        default="India · Partnering worldwide", max_length=180
                    ),
                ),
                ("map_embed_url", models.URLField(blank=True)),
                (
                    "footer_text",
                    models.CharField(
                        default="Independent thinking. Relentless execution.",
                        max_length=150,
                    ),
                ),
                ("accent_color", models.CharField(default="#c7ff4a", max_length=20)),
                (
                    "background_color",
                    models.CharField(default="#080a09", max_length=20),
                ),
                ("font_heading", models.CharField(default="Manrope", max_length=80)),
                ("font_body", models.CharField(default="Inter", max_length=80)),
                ("analytics_id", models.CharField(blank=True, max_length=40)),
            ],
            options={
                "verbose_name_plural": "Site settings",
            },
        ),
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("platform", models.CharField(max_length=40)),
                ("url", models.URLField()),
            ],
            options={
                "ordering": ("order", "id"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Statistic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("value", models.CharField(max_length=20)),
                ("label", models.CharField(max_length=80)),
            ],
            options={
                "ordering": ("order", "id"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Technology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=60)),
                ("short_code", models.CharField(max_length=8)),
            ],
            options={
                "ordering": ("order", "id"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("quote", models.TextField()),
                ("client_name", models.CharField(max_length=80)),
                ("role", models.CharField(max_length=100)),
                ("company", models.CharField(max_length=100)),
                ("avatar_url", models.URLField(blank=True)),
                ("rating", models.PositiveSmallIntegerField(default=5)),
            ],
            options={
                "ordering": ("order", "id"),
                "abstract": False,
            },
        ),
    ]
