# Generated by Django 6.0.5 on 2026-07-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("excerpt", models.TextField()),
                ("content", models.TextField()),
                ("category", models.CharField(max_length=80)),
                (
                    "author",
                    models.CharField(default="The Webfix Editorial", max_length=100),
                ),
                ("featured_image", models.ImageField(blank=True, upload_to="blog/")),
                ("image_alt", models.CharField(blank=True, max_length=180)),
                ("meta_title", models.CharField(max_length=70)),
                ("meta_description", models.CharField(max_length=170)),
                ("published_at", models.DateTimeField()),
                ("is_published", models.BooleanField(default=True)),
                ("featured", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ("-published_at",),
            },
        ),
        migrations.CreateModel(
            name="Brochure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="The Webfix Company Profile", max_length=100
                    ),
                ),
                ("file", models.FileField(upload_to="brochures/")),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CareerOpening",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=100)),
                (
                    "location",
                    models.CharField(default="Remote / India", max_length=100),
                ),
                (
                    "employment_type",
                    models.CharField(default="Full-time", max_length=50),
                ),
                ("description", models.TextField()),
                (
                    "apply_email",
                    models.EmailField(default="info@thewebfix.in", max_length=254),
                ),
            ],
            options={
                "ordering": ("order", "id"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=100)),
                ("industry", models.CharField(max_length=80)),
                ("logo", models.ImageField(blank=True, upload_to="clients/")),
                ("logo_text", models.CharField(blank=True, max_length=12)),
                ("result", models.CharField(blank=True, max_length=140)),
                ("website", models.URLField(blank=True)),
            ],
            options={
                "ordering": ("order", "id"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ContentPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page_type",
                    models.CharField(
                        choices=[
                            ("about", "About"),
                            ("founder", "Founder"),
                            ("clients", "Our Clients"),
                            ("careers", "Careers"),
                            ("contact", "Contact"),
                            ("privacy", "Privacy Policy"),
                            ("terms", "Terms"),
                            ("refund", "Refund Policy"),
                            ("disclaimer", "Disclaimer"),
                        ],
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("eyebrow", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=180)),
                ("introduction", models.TextField()),
                ("body", models.TextField(blank=True)),
                ("mission", models.TextField(blank=True)),
                ("vision", models.TextField(blank=True)),
                ("values", models.TextField(blank=True, help_text="One item per line")),
                ("image", models.ImageField(blank=True, upload_to="pages/")),
                ("meta_title", models.CharField(max_length=70)),
                ("meta_description", models.CharField(max_length=170)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="FounderProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "role",
                    models.CharField(
                        default="Founder & Managing Director", max_length=100
                    ),
                ),
                ("short_bio", models.TextField()),
                ("biography", models.TextField()),
                ("vision", models.TextField()),
                ("experience", models.CharField(max_length=80)),
                (
                    "achievements",
                    models.TextField(help_text="One achievement per line"),
                ),
                ("message", models.TextField()),
                ("portrait", models.ImageField(blank=True, upload_to="founder/")),
                ("linkedin_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="NewsletterSubscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name="service",
            name="benefits",
            field=models.TextField(blank=True, help_text="One benefit per line"),
        ),
        migrations.AddField(
            model_name="service",
            name="eyebrow",
            field=models.CharField(default="Digital capability", max_length=100),
        ),
        migrations.AddField(
            model_name="service",
            name="features",
            field=models.TextField(blank=True, help_text="One feature per line"),
        ),
        migrations.AddField(
            model_name="service",
            name="hero_image",
            field=models.ImageField(blank=True, upload_to="services/"),
        ),
        migrations.AddField(
            model_name="service",
            name="meta_description",
            field=models.CharField(blank=True, max_length=170),
        ),
        migrations.AddField(
            model_name="service",
            name="meta_title",
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name="service",
            name="overview",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="service",
            name="process",
            field=models.TextField(blank=True, help_text="One process step per line"),
        ),
        migrations.AddField(
            model_name="service",
            name="slug",
            field=models.SlugField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="service",
            name="technologies",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="logo",
            field=models.ImageField(blank=True, upload_to="branding/"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="office_hours",
            field=models.CharField(
                default="Monday–Saturday · 10:00–19:00 IST", max_length=120
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="secondary_phone",
            field=models.CharField(default="9755838625", max_length=40),
        ),
    ]
