# Generated by Django 6.0.5 on 2026-07-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_blogpost_brochure_careeropening_client_contentpage_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("description", models.TextField()),
                ("features", models.TextField(help_text="One feature per line")),
                ("image", models.ImageField(blank=True, upload_to="products/")),
                ("image_alt", models.CharField(max_length=180)),
                (
                    "cta_text",
                    models.CharField(default="Explore solution", max_length=50),
                ),
                ("cta_url", models.CharField(default="/contact/", max_length=180)),
            ],
            options={
                "ordering": ("order", "id"),
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_background",
            field=models.ImageField(blank=True, upload_to="site/"),
        ),
    ]
