# Generated by Django 6.0.5 on 2026-07-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_product_sitesettings_hero_background"),
    ]

    operations = [
        migrations.AddField(
            model_name="testimonial",
            name="website_url",
            field=models.URLField(blank=True),
        ),
    ]
