# Generated by Django 6.0.5 on 2026-07-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0004_testimonial_website_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="testimonial",
            name="website_urls",
            field=models.TextField(blank=True),
        ),
    ]
