# Generated by Django 6.0.5 on 2026-07-24 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0006_jobapplication"),
    ]

    operations = [
        migrations.AddField(
            model_name="faq",
            name="category",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("website", "Website Development"),
                    ("seo", "SEO"),
                    ("social", "Social Media"),
                    ("software", "Software & SaaS"),
                    ("hosting", "Hosting & Support"),
                    ("commercial", "Pricing & Process"),
                    ("policy", "Policies"),
                ],
                default="general",
                max_length=20,
            ),
        ),
    ]
